site_name: LeetCode Solutions
site_description: My LeetCode solutions
site_url: https://alexengrig.github.io/leetcode/
repo_url: https://github.com/alexengrig/leetcode
repo_name: alexengrig/leetcode

docs_dir: site-docs
site_dir: site

theme:
  name: material
  features:
    - navigation.sections
    - navigation.indexes
    - content.code.copy
    - content.code.select
    - search.suggest
    - search.highlight

plugins:
  - search

markdown_extensions:
  - admonition
  - toc:
      permalink: true
  - pymdownx.highlight
  - pymdownx.superfences
  - pymdownx.details

nav:
  - Home: index.md
  - Problems: problems/index.md
